name: Checked Code
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Setup Velociraptor
        uses: jurassiscripts/setup-velociraptor@v2
      - name: Lint
        run: deno lint
      - name: Format Check
        run: deno fmt --check --ignore=README.md,./.github/
      - name: Unit Test
        run: vr test
      - name: Unit Test
        run: deno test test/e2e/ --allow-net --allow-run --config ./tsconfig.json