name: Checked Code
on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.x
      - name: Setup Velociraptor
        uses: jurassiscripts/setup-velociraptor@v2
      - name: Lint
        run: deno lint
      - name: Format Check
        run: deno fmt --check --ignore=README.md,.github/,sample/
      - name: Unit Test
        run: vr test
      - uses: actions/github-script@v3
        id: get-preview-url
        with:
          script: |
            const commitStatus = await github.repos.listCommitStatusesForRef({
              owner: "windchime-yk",
              repo: "unrewrite",
              ref: context.payload.after,
            })
            const { data } = await commitStatus
            return data[0].target_url
      - name: E2E Test
        run: BASE_URL=${{ steps.get-preview-url.outputs.result }} deno test --allow-net --allow-run --allow-env test/e2e/